#!/usr/bin/env python3
"""Add consistent navigation/backlink blocks to tutorial index files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

INDEX_NAME = "index.md"
NAV_HEADING = "## Navigation & Backlinks"
GENERATED_MARKER = "*Generated by [AI Codebase Knowledge Builder]"
NUMBERED_FILE_RE = re.compile(r"^([0-9]{2,})[-_].+\.md$")


def first_heading(markdown: str) -> str:
    for line in markdown.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def chapter_files(tutorial_dir: Path) -> list[Path]:
    chapters: list[tuple[int, str, Path]] = []
    for path in tutorial_dir.glob("*.md"):
        if path.name == INDEX_NAME:
            continue
        match = NUMBERED_FILE_RE.match(path.name)
        if not match:
            continue
        number = int(match.group(1))
        chapters.append((number, path.name, path))
    chapters.sort(key=lambda item: (item[0], item[1]))
    return [item[2] for item in chapters]


def nav_block_for_tutorial(tutorial_dir: Path) -> str:
    chapters = chapter_files(tutorial_dir)
    if chapters:
        first_chapter = chapters[0]
        heading = first_heading(first_chapter.read_text(encoding="utf-8", errors="ignore"))
        if not heading:
            heading = first_chapter.stem.replace("-", " ").replace("_", " ").title()
        start_link = f"- [Start Here: {heading}]({first_chapter.name})"
    else:
        start_link = "- [Browse Tutorial Directory](../../discoverability/tutorial-directory.md)"

    lines = [
        NAV_HEADING,
        "",
        start_link,
        "- [Back to Main Catalog](../../README.md#-tutorial-catalog)",
        "- [Browse A-Z Tutorial Directory](../../discoverability/tutorial-directory.md)",
        "- [Search by Intent](../../discoverability/query-hub.md)",
        "- [Explore Category Hubs](../../README.md#category-hubs)",
    ]
    return "\n".join(lines)


def insert_nav_block(original: str, block: str) -> tuple[str, bool]:
    if NAV_HEADING in original:
        return original, False

    if GENERATED_MARKER in original:
        before, after = original.split(GENERATED_MARKER, 1)
        updated = before.rstrip() + "\n\n" + block + "\n\n" + GENERATED_MARKER + after
        return updated, True

    updated = original.rstrip() + "\n\n" + block + "\n"
    return updated, True


def main() -> int:
    parser = argparse.ArgumentParser(description="Add navigation/backlink block to tutorial indexes")
    parser.add_argument("--root", default=".", help="Repository root")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    tutorials_root = root / "tutorials"

    updated_count = 0
    skipped_count = 0

    for tutorial_dir in sorted(p for p in tutorials_root.iterdir() if p.is_dir()):
        index_path = tutorial_dir / INDEX_NAME
        if not index_path.is_file():
            continue
        original = index_path.read_text(encoding="utf-8", errors="ignore")
        block = nav_block_for_tutorial(tutorial_dir)
        updated, changed = insert_nav_block(original, block)
        if changed:
            index_path.write_text(updated, encoding="utf-8")
            updated_count += 1
        else:
            skipped_count += 1

    print(f"updated_index_count={updated_count}")
    print(f"skipped_index_count={skipped_count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
